services:
  pdfgenrs:
    image: ghcr.io/navikt/pdfgenrs:0.1.84
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - DEV_MODE=true
    volumes:
      - ./templates:/app/templates
      - ./data:/app/data
      - ./fonts:/app/fonts
      - ./resources:/app/resources
