apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pdfgenrs-test
  namespace: pdfgen
  labels:
    team: pdfgen
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics
  leaderElection: false
  observability:
    logging:
      destinations:
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: sdk
  ingresses:
    - "https://pdfgenrs-test.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 7m
      memory: 128Mi
