name: Deploy to dev
on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    permissions:
      packages: "write"
      contents: "read"
      id-token: "write"
    name: Checkout code and create docker tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: docker-build-push
        uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512 # v0
        id: docker-build-push
        with:
          team: pdfgen
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: naiserator-dev.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
